"""
Seed accounts, transfers, and a known-fraud profile set (with embeddings) for the
fraud-ring demo. Run:  python src/seed.py
"""
from __future__ import annotations

import asyncio

from openai import AsyncOpenAI

import config
from mcp_oracle import open_oracle_mcp, OracleMCP

# account_id, name, profile_text
ACCOUNTS = [
    (201, "Shell Holdings", "Newly registered entity with no employees that only moves large round-number sums between related companies."),
    (202, "Quartz Trading", "Minimal real business activity; rapidly forwards incoming funds onward to other opaque entities."),
    (203, "Nimbus LLC", "Opaque ownership; used to cycle money back to the original sender after a couple of hops."),
    (204, "Acme Retail", "Established storefront with regular payroll, taxes, and steady supplier payments."),
    (205, "Bright Foods", "Regional food distributor with recurring monthly invoices to known vendors."),
    (206, "Cedar Supplies", "Long-standing office-supplies vendor with consistent, modest monthly transactions."),
]

# from_acct, to_acct, amount  (201->202->203->201 is a laundering ring of round-number sums)
TRANSFERS = [
    (201, 202, 250000),
    (202, 203, 245000),
    (203, 201, 240000),
    (204, 205, 1280),
    (205, 206, 940),
    (202, 204, 60000),   # ring leaking into a real business
]

# historical known-fraud profiles for the vector flag
KNOWN_FRAUD = [
    "Shell company with no genuine operations that layers funds through circular, round-number transfers.",
    "Front entity that receives money and immediately forwards it to related accounts to obscure its origin.",
    "Pass-through company used to cycle money back to the originator, hiding the true source of funds.",
]


def _q(t: str) -> str:
    t = (t or "").replace("'", "''")
    return "'" + (t.replace("&", "'||CHR(38)||'") if "&" in t else t) + "'"


def _vlit(v):
    return "[" + ",".join(f"{x:.6f}" for x in v) + "]"


async def _run(mcp: OracleMCP, sql: str, what: str) -> None:
    out = await mcp.run_sql(sql)
    if "ORA-" in out or "Error" in out or "cancelled" in out:
        raise RuntimeError(f"{what} FAILED:\n" + next((l for l in out.splitlines() if 'ORA-' in l), out[:400]))
    print(f"  · {what}")


async def main() -> None:
    client = AsyncOpenAI(api_key=config.OPENAI_API_KEY or None)
    print(f"Embedding {len(ACCOUNTS)+len(KNOWN_FRAUD)} profiles with {config.EMBED_MODEL} ...")
    acc_vecs = (await client.embeddings.create(model=config.EMBED_MODEL, input=[a[2] for a in ACCOUNTS])).data
    kf_vecs = (await client.embeddings.create(model=config.EMBED_MODEL, input=KNOWN_FRAUD)).data

    async with open_oracle_mcp(config.SQLCL_COMMAND, config.ORACLE_MCP_CONNECTION) as mcp:
        print(f"Connected via SQLcl MCP (connection '{config.ORACLE_MCP_CONNECTION}').\n")
        await mcp.run_sqlcl("set define off")

        print("Creating tables ...")
        for t in ("TRANSFERS", "ACCOUNTS", "KNOWN_FRAUD"):
            await mcp.run_sql(f"BEGIN EXECUTE IMMEDIATE 'DROP TABLE {t} CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;")
        await _run(mcp, "CREATE TABLE accounts (account_id NUMBER PRIMARY KEY, name VARCHAR2(80), "
                   "profile_text VARCHAR2(2000), embedding VECTOR(1536, FLOAT32))", "accounts")
        await _run(mcp, "CREATE TABLE transfers (from_acct NUMBER, to_acct NUMBER, amount NUMBER, "
                   "ts DATE DEFAULT SYSDATE)", "transfers")
        await _run(mcp, "CREATE TABLE known_fraud (fraud_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                   "profile_text VARCHAR2(2000), embedding VECTOR(1536, FLOAT32))", "known_fraud")

        print("Loading accounts + embeddings ...")
        for (aid, nm, prof), v in zip(ACCOUNTS, acc_vecs):
            await mcp.run_sql("INSERT INTO accounts (account_id,name,profile_text,embedding) VALUES "
                              f"({aid},{_q(nm)},{_q(prof)},TO_VECTOR('{_vlit(v.embedding)}'))")
        print(f"  · {len(ACCOUNTS)} accounts")

        print("Loading transfers ...")
        rows = "\n".join(f"  INTO transfers (from_acct,to_acct,amount) VALUES ({f},{t},{a})" for (f, t, a) in TRANSFERS)
        await _run(mcp, f"INSERT ALL\n{rows}\nSELECT 1 FROM DUAL", f"{len(TRANSFERS)} transfers")

        print("Loading known-fraud profiles + embeddings ...")
        for prof, v in zip(KNOWN_FRAUD, kf_vecs):
            await mcp.run_sql("INSERT INTO known_fraud (profile_text,embedding) VALUES "
                              f"({_q(prof)},TO_VECTOR('{_vlit(v.embedding)}'))")
        print(f"  · {len(KNOWN_FRAUD)} known-fraud profiles")

        await mcp.run_sql("COMMIT")
        print("\nDone. Seed complete.")


if __name__ == "__main__":
    asyncio.run(main())
