-- ============================================================================
--  Fraud-ring detection — reference schema (recursive SQL + vectors)
-- ============================================================================
CREATE TABLE accounts (account_id NUMBER PRIMARY KEY, name VARCHAR2(80),
  profile_text VARCHAR2(2000), embedding VECTOR(1536, FLOAT32));
CREATE TABLE transfers (from_acct NUMBER, to_acct NUMBER, amount NUMBER, ts DATE DEFAULT SYSDATE);
CREATE TABLE known_fraud (fraud_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_text VARCHAR2(2000), embedding VECTOR(1536, FLOAT32));

-- Detect transfer cycles with a recursive query (runs as any user):
--   WITH paths (start_acct, cur_acct, depth, pth) AS (
--     SELECT from_acct, to_acct, 1, '-'||from_acct||'-'||to_acct||'-' FROM transfers
--     UNION ALL
--     SELECT p.start_acct, t.to_acct, p.depth+1, p.pth||t.to_acct||'-'
--     FROM paths p JOIN transfers t ON t.from_acct = p.cur_acct
--     WHERE p.depth < 5 AND (t.to_acct = p.start_acct OR INSTR(p.pth,'-'||t.to_acct||'-')=0))
--   SELECT pth FROM paths WHERE cur_acct = start_acct;

-- Equivalent with a SQL PROPERTY GRAPH (needs CREATE PROPERTY GRAPH privilege):
--   CREATE PROPERTY GRAPH money VERTEX TABLES (accounts KEY(account_id))
--     EDGE TABLES (transfers KEY(from_acct,to_acct)
--       SOURCE KEY(from_acct) REFERENCES accounts(account_id)
--       DESTINATION KEY(to_acct) REFERENCES accounts(account_id));
--   SELECT * FROM GRAPH_TABLE(money
--     MATCH (a)-[]->(b)-[]->(c)-[]->(a) COLUMNS (a.name, b.name, c.name));

-- Confirm members look like known fraud (vector search):
--   SELECT a.name, MIN(VECTOR_DISTANCE(a.embedding, k.embedding, COSINE)) AS fraud_dist
--   FROM accounts a, known_fraud k GROUP BY a.name ORDER BY fraud_dist;
